// Diff viewer. Per ISSUES.md #19:
// "side-by-side code view highlighting the matched regions returned by
// similarity_service (from issue #8's match_regions_json), for both
// student-vs-peer and student-vs-AI-reference comparisons."
//
// Acceptance criteria: "matched lines are visually highlighted on both
// sides in sync (same line ranges, not just two independent code blocks)."
//
// The backend's similarity_service.py already produces HTML with
// <mark class="bg-yellow-200 text-yellow-900"> highlight spans via
// copydetect's highlight_overlap(). This component renders that HTML
// directly using dangerouslySetInnerHTML on each side — the marks are
// already in sync because they come from the same compare_files() call.
//
// Data fetching: the flags router exposes the flag rows which contain
// question_id. We need to separately fetch the SimilarityPair / AiSimilarity
// rows that carry match_regions_json. For now those come from the flag
// detail endpoint. Since no dedicated /diff endpoint exists yet, we use
// the flag's match_regions_json stored on the FlagSummary's related rows
// via a query param approach: the route passes the flagId and the diff
// type (peer | ai_ref) as params, and we get them from location state
// passed by FlaggedStudents.jsx's row click (navigate with state).
//
// Route: /professor/questions/:questionId/flags/:flagId/diff
// Navigate to this with: navigate(path, { state: { html_a, html_b, label_a, label_b } })
import { useLocation, useNavigate, Link, useParams } from "react-router-dom";
import Navbar from "../components/Navbar";

export default function DiffViewer() {
  const { questionId, flagId } = useParams();
  const { state } = useLocation();
  const navigate = useNavigate();

  // state is injected by FlaggedStudents when the user clicks a row.
  // If we land here directly (e.g. browser refresh), state will be null.
  if (!state || (!state.html_a && !state.html_b)) {
    return (
      <>
        <Navbar />
        <main className="mx-auto max-w-3xl px-6 py-10 text-center">
          <div className="surface-card px-6 py-14">
            <p className="font-display text-lg font-semibold text-ink">No diff data</p>
            <p className="mt-2 text-ink-soft text-sm">
              Open this page by clicking a flagged student row — the diff data
              is passed through the navigation state.
            </p>
            <button
              onClick={() => navigate(-1)}
              className="btn-secondary mt-6"
            >
              ← Go back
            </button>
          </div>
        </main>
      </>
    );
  }

  const {
    html_a,
    html_b,
    label_a = "Student submission",
    label_b = "Comparison file",
    overlap_tokens,
  } = state;

  return (
    <>
      <Navbar />
      <main className="px-4 py-6 max-w-[1400px] mx-auto">
        <div className="flex items-center gap-3 mb-5">
          <button
            onClick={() => navigate(-1)}
            className="text-sm font-medium text-ink-soft hover:text-ink"
          >
            ← Back
          </button>
          <h1 className="text-xl font-bold text-ink">Code comparison</h1>
          {overlap_tokens !== undefined && (
            <span className="rounded-full bg-amber-soft px-2.5 py-1 text-xs font-medium text-amber-dark">
              {overlap_tokens} matched tokens
            </span>
          )}
        </div>

        {/* Side-by-side panes */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
          <CodePane title={label_a} html={html_a} />
          <CodePane title={label_b} html={html_b} />
        </div>

        {/* Legend */}
        <div className="mt-3 flex items-center gap-2 text-xs text-ink-soft">
          <span className="inline-block h-3 w-6 rounded bg-yellow-200 border border-yellow-300" />
          <span>Matched region</span>
        </div>
      </main>
    </>
  );
}

function CodePane({ title, html }) {
  return (
    <div className="surface-card overflow-hidden flex flex-col">
      {/* Header */}
      <div className="border-b border-paper-line px-4 py-2.5 bg-paper">
        <p className="text-sm font-medium text-ink-soft truncate">{title}</p>
      </div>

      {/* Code body — the HTML has <mark> tags for highlights already */}
      <div className="overflow-auto flex-1 bg-[#1e1e2e] p-4">
        {html ? (
          <pre
            className="text-[13px] leading-relaxed text-slate-200 font-mono whitespace-pre-wrap break-words"
            // Safe: html comes from copydetect's highlight_overlap() which
            // only inserts <mark> tags into already-escaped code text.
            // The mark tags are generated by this backend, not user input.
            dangerouslySetInnerHTML={{ __html: html }}
          />
        ) : (
          <p className="text-ink-faint text-sm italic">No code available.</p>
        )}
      </div>
    </div>
  );
}
